# Generated by Django 5.2.11 on 2026-03-31 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0002_listingconversation_soft_delete_fields"),
        ("listings", "0015_listingreport_listingreview_listing_approval_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="listingconversation",
            name="unique_listing_conversation_participant",
        ),
        migrations.AddField(
            model_name="listingconversation",
            name="conversation_type",
            field=models.CharField(
                choices=[("listing", "Listing"), ("direct", "Direct")], db_index=True, default="listing", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="listingconversation",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="listings.listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingconversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("conversation_type", "listing")),
                fields=("listing", "participant"),
                name="unique_listing_conversation_participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingconversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("conversation_type", "direct")),
                fields=("owner", "participant"),
                name="unique_direct_conversation_pair",
            ),
        ),
    ]
