# Generated by Django 5.2.11 on 2026-04-19 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communications", "0003_remove_listingconversation_unique_listing_conversation_participant_and_more"),
        ("listings", "0024_one_group_per_user"),
        ("users", "0019_favoriteroommate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="RoommateGroup",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("name", models.CharField(max_length=120)),
                        ("description", models.TextField(blank=True)),
                        ("is_active", models.BooleanField(db_index=True, default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "lead",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="led_roommate_group",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "listings_roommategroup",
                        "ordering": ["-updated_at", "-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="RoommateGroupInvite",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending_approval", "Awaiting group approval"),
                                    ("pending_invitee", "Awaiting invitee response"),
                                    ("accepted", "Accepted"),
                                    ("rejected", "Rejected"),
                                    ("cancelled", "Cancelled"),
                                ],
                                db_index=True,
                                default="pending_approval",
                                max_length=24,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("responded_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "conversation",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="roommate_group_invites",
                                to="communications.listingconversation",
                            ),
                        ),
                        (
                            "group",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="invites",
                                to="roommates.roommategroup",
                            ),
                        ),
                        (
                            "invitee",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="received_roommate_group_invites",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "inviter",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="sent_roommate_group_invites",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "users_roommategroupinvite",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="RoommateGroupInviteApproval",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("approved", models.BooleanField(null=True)),
                        ("responded_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "invite",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="approvals",
                                to="roommates.roommategroupinvite",
                            ),
                        ),
                        (
                            "member",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="roommate_group_invite_approvals",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "users_roommategroupinviteapproval",
                    },
                ),
                migrations.CreateModel(
                    name="RoommateGroupMembership",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "group",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="memberships",
                                to="roommates.roommategroup",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="roommate_memberships",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "listings_roommategroupmembership",
                        "ordering": ["created_at", "id"],
                    },
                ),
                migrations.AddField(
                    model_name="roommategroup",
                    name="members",
                    field=models.ManyToManyField(
                        related_name="roommate_groups",
                        through="roommates.RoommateGroupMembership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.CreateModel(
                    name="RoommatePost",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("title", models.CharField(max_length=120)),
                        ("description", models.TextField()),
                        (
                            "housing_status",
                            models.CharField(
                                choices=[("have_home", "Already have a place"), ("need_home", "Still need a place")],
                                db_index=True,
                                default="need_home",
                                max_length=16,
                            ),
                        ),
                        ("current_group_size", models.PositiveSmallIntegerField(default=1)),
                        ("open_spots", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                        ("budget_min", models.DecimalField(decimal_places=0, max_digits=8)),
                        ("budget_max", models.DecimalField(decimal_places=0, max_digits=8)),
                        ("move_in_date", models.DateField(db_index=True)),
                        ("neighborhoods", models.CharField(blank=True, max_length=240)),
                        ("is_active", models.BooleanField(db_index=True, default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "author",
                            models.OneToOneField(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="roommate_post",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "group",
                            models.OneToOneField(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="roommate_post",
                                to="roommates.roommategroup",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "listings_roommatepost",
                        "ordering": ["-updated_at", "-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="FavoriteRoommate",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "favorite_user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="favorited_by_students",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="favorite_roommates",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "users_favoriteroommate",
                        "ordering": ["-created_at"],
                        "indexes": [
                            models.Index(fields=["user", "created_at"], name="favorite_roommate_user_idx"),
                            models.Index(fields=["favorite_user", "created_at"], name="favorite_roommate_target_idx"),
                        ],
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("user", "favorite_user"), name="favorite_roommate_unique_pair"
                            ),
                            models.CheckConstraint(
                                condition=models.Q(("user", models.F("favorite_user")), _negated=True),
                                name="favorite_roommate_user_ne_favorite_user",
                            ),
                        ],
                    },
                ),
                migrations.AddIndex(
                    model_name="roommategroupinvite",
                    index=models.Index(fields=["invitee", "status", "created_at"], name="rg_invite_in_idx"),
                ),
                migrations.AddIndex(
                    model_name="roommategroupinvite",
                    index=models.Index(fields=["group", "status", "created_at"], name="rg_invite_group_idx"),
                ),
                migrations.AddConstraint(
                    model_name="roommategroupinvite",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending_approval", "pending_invitee"])),
                        fields=("group", "invitee"),
                        name="roommate_group_invite_active_unique",
                    ),
                ),
                migrations.AddIndex(
                    model_name="roommategroupinviteapproval",
                    index=models.Index(fields=["member", "responded_at"], name="rg_invite_approval_mem_idx"),
                ),
                migrations.AddConstraint(
                    model_name="roommategroupinviteapproval",
                    constraint=models.UniqueConstraint(
                        fields=("invite", "member"),
                        name="roommate_group_invite_approval_unique",
                    ),
                ),
                migrations.AddIndex(
                    model_name="roommategroupmembership",
                    index=models.Index(fields=["group", "created_at"], name="roommate_group_member_idx"),
                ),
                migrations.AddIndex(
                    model_name="roommategroupmembership",
                    index=models.Index(fields=["user", "created_at"], name="roommate_group_user_idx"),
                ),
                migrations.AddConstraint(
                    model_name="roommategroupmembership",
                    constraint=models.UniqueConstraint(
                        fields=("group", "user"), name="roommate_group_membership_unique"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="roommategroupmembership",
                    constraint=models.UniqueConstraint(
                        fields=("user",), name="roommate_group_membership_one_group_per_user"
                    ),
                ),
                migrations.AddIndex(
                    model_name="roommategroup",
                    index=models.Index(fields=["is_active", "updated_at"], name="roommate_group_active_idx"),
                ),
                migrations.AddIndex(
                    model_name="roommatepost",
                    index=models.Index(fields=["is_active", "updated_at"], name="roommate_post_active_idx"),
                ),
                migrations.AddIndex(
                    model_name="roommatepost",
                    index=models.Index(fields=["housing_status", "move_in_date"], name="roommate_post_housing_idx"),
                ),
                migrations.AddConstraint(
                    model_name="roommatepost",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("author__isnull", False), ("group__isnull", True)),
                            models.Q(("author__isnull", True), ("group__isnull", False)),
                            _connector="OR",
                        ),
                        name="roommate_post_exactly_one_owner",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="roommatepost",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("housing_status__in", ("have_home", "need_home"))),
                        name="roommate_post_housing_status_valid",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="roommatepost",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("current_group_size__gte", 1)),
                        name="roommate_post_group_size_gte_one",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="roommatepost",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("housing_status", "have_home"), ("open_spots__gte", 1)),
                            models.Q(
                                ("housing_status__in", ["need_home"]),
                                models.Q(("open_spots__isnull", True), ("open_spots__gte", 1), _connector="OR"),
                            ),
                            _connector="OR",
                        ),
                        name="roommate_post_open_spots_valid",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="roommatepost",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("budget_min__gte", 0)),
                        name="roommate_post_budget_min_gte_zero",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="roommatepost",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("budget_max__gte", 0)),
                        name="roommate_post_budget_max_gte_zero",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="roommatepost",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("budget_max__gte", models.F("budget_min"))),
                        name="roommate_post_budget_max_gte_min",
                    ),
                ),
            ],
        )
    ]
