# Generated by Django 5.2.11 on 2026-03-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
