# Generated by Django 5.2.12 on 2026-03-16 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userfile_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_name", models.CharField(blank=True, max_length=120)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=32)),
                ("bio", models.CharField(blank=True, max_length=300)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),  # noqa: E501
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_name", models.CharField(blank=True, max_length=120)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=32)),
                ("major", models.CharField(blank=True, max_length=120)),
                ("bio", models.CharField(blank=True, max_length=300)),
                ("messy_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("guest_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bedtime", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("noise_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("smoke", models.BooleanField(default=False)),
                ("drink", models.BooleanField(default=False)),
                ("party", models.BooleanField(default=False)),
                ("pets", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),  # noqa: E501
            ],
        ),
    ]
