# Generated by Django 5.2.12 on 2026-03-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_adminprofile_studentprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("rental_agent", "Rental Agent"), ("admin", "Admin")],
                default="student",
                help_text="Designates whether this user is a Student or Admin.",
                max_length=12,
            ),
        ),
    ]
