# Generated by Django 5.2.12 on 2026-03-16 00:00

from django.db import migrations, models


def sync_realtor_role_forward(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    CustomUser.objects.filter(role="rental_agent").update(role="realtor")


def sync_realtor_role_backward(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    CustomUser.objects.filter(role="realtor").update(role="rental_agent")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_role"),
    ]

    operations = [
        migrations.RunPython(sync_realtor_role_forward, sync_realtor_role_backward),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("realtor", "Realtor"), ("admin", "Admin")],
                default="student",
                help_text="Access level for the housing platform.",
                max_length=12,
            ),
        ),
    ]
