# Generated by Django 5.2.11 on 2026-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_sync_realtor_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("realtor", "Realtor"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="student",
                help_text="Access level for the housing platform.",
                max_length=12,
            ),
        ),
    ]
