# Generated by Django 5.2.11 on 2026-03-17 17:00

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_email_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(
                upload_to="user_uploads/%Y/%m/%d",
                validators=[users.validators.validate_user_upload],
            ),
        ),
    ]
