# Generated by Django 5.2.11 on 2026-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_userfile_file"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userfile",
            index=models.Index(fields=["owner", "uploaded_at"], name="userfile_owner_uploaded_idx"),
        ),
    ]
