# Generated by Django 5.2.11 on 2026-03-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_userfile_userfile_owner_uploaded_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="legal_policy_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="customuser",
            name="privacy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
