# Generated by Django 5.2.11 on 2026-03-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0011_customuser_profile_image_url"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["student", "realtor", "admin"])),
                name="customuser_role_valid",
            ),
        ),
    ]
