# Generated by Django 5.2.12 on 2026-04-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_profile_ui_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uploaded_avatar",
            field=models.ImageField(blank=True, upload_to="avatars/"),
        ),
    ]
