# Generated by Django 5.2.11 on 2026-04-06 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0003_remove_listingconversation_unique_listing_conversation_participant_and_more"),
        ("users", "0015_customuser_uploaded_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoommateGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_roommate_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoommateGroupInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Awaiting group approval"),
                            ("pending_invitee", "Awaiting invitee response"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending_approval",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roommate_group_invites",
                        to="communications.listingconversation",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="users.roommategroup",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_roommate_group_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_roommate_group_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["invitee", "status", "created_at"], name="rg_invite_in_idx"),
                    models.Index(fields=["group", "status", "created_at"], name="rg_invite_group_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoommateGroupInviteApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approved", models.BooleanField(null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="users.roommategroupinvite",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_group_invite_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["member", "responded_at"], name="rg_invite_approval_mem_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoommateGroupMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="users.roommategroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "indexes": [
                    models.Index(fields=["user", "joined_at"], name="roommate_group_member_user_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="roommategroupmember",
            constraint=models.UniqueConstraint(fields=("group", "user"), name="roommate_group_member_unique"),
        ),
        migrations.AddConstraint(
            model_name="roommategroupinvite",
            constraint=models.UniqueConstraint(
                fields=("group", "invitee"),
                condition=models.Q(status__in=["pending_approval", "pending_invitee"]),
                name="roommate_group_invite_active_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="roommategroupinviteapproval",
            constraint=models.UniqueConstraint(
                fields=("invite", "member"), name="roommate_group_invite_approval_unique"
            ),
        ),
    ]
