# Generated by Django 5.2.11 on 2026-04-11 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_roommate_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommategroupmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_roommate_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
