# Generated by Django 5.2.12 on 2026-04-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0024_one_group_per_user"),
        ("users", "0017_alter_roommategroupmember_user"),
    ]

    operations = [
        # Clear legacy invite/membership data before re-pointing the FK.
        # Existing rows reference users.RoommateGroup PKs which are incompatible
        # with listings.RoommateGroup after this migration.
        migrations.RunSQL("DELETE FROM users_roommategroupinviteapproval;", migrations.RunSQL.noop),
        migrations.RunSQL("DELETE FROM users_roommategroupinvite;", migrations.RunSQL.noop),
        migrations.RunSQL("DELETE FROM users_roommategroupmember;", migrations.RunSQL.noop),
        migrations.RunSQL("DELETE FROM users_roommategroup;", migrations.RunSQL.noop),
        migrations.AlterField(
            model_name="roommategroupinvite",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="listings.roommategroup"
            ),
        ),
    ]
