# Generated by Django 5.2.12 on 2026-04-17 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_rewire_invite_group_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteRoommate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "favorite_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_roommates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="favorite_roommate_user_idx"),
                    models.Index(fields=["favorite_user", "created_at"], name="favorite_roommate_target_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "favorite_user"), name="favorite_roommate_unique_pair"),
                    models.CheckConstraint(
                        condition=models.Q(("user", models.F("favorite_user")), _negated=True),
                        name="favorite_roommate_user_ne_favorite_user",
                    ),
                ],
            },
        ),
    ]
