# Generated by Django 5.2.11 on 2026-04-19 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roommates", "0001_initial"),
        ("users", "0019_favoriteroommate"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="FavoriteRoommate"),
                migrations.DeleteModel(name="RoommateGroup"),
                migrations.DeleteModel(name="RoommateGroupInvite"),
                migrations.DeleteModel(name="RoommateGroupInviteApproval"),
                migrations.DeleteModel(name="RoommateGroupMember"),
            ],
        )
    ]
