# Generated by Django 5.2.13 on 2026-04-21 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_existing_access_data(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    StudentProfile = apps.get_model("users", "StudentProfile")
    AdminProfile = apps.get_model("users", "AdminProfile")

    CustomUser.objects.filter(role="admin").update(role="platform_admin")

    valid_genders = {"male", "female", "other", "prefer_not", ""}
    valid_scale_values = {1, 2, 3, 4, 5}

    for profile in StudentProfile.objects.all():
        changed_fields = []
        if profile.age is not None and not 16 <= profile.age <= 99:
            profile.age = None
            changed_fields.append("age")
        if profile.gender not in valid_genders:
            profile.gender = ""
            profile.gender_other = ""
            changed_fields.extend(["gender", "gender_other"])
        elif profile.gender != "other" and profile.gender_other:
            profile.gender_other = ""
            changed_fields.append("gender_other")
        for field_name in ("messy_level", "guest_level", "noise_level", "drink", "party"):
            value = getattr(profile, field_name)
            if value is not None and value not in valid_scale_values:
                setattr(profile, field_name, None)
                changed_fields.append(field_name)
        if profile.bedtime is not None and not 0 <= profile.bedtime <= 23:
            profile.bedtime = None
            changed_fields.append("bedtime")
        if changed_fields:
            profile.save(update_fields=changed_fields)

    for profile in AdminProfile.objects.all():
        changed_fields = []
        if profile.age is not None and not 16 <= profile.age <= 99:
            profile.age = None
            changed_fields.append("age")
        if profile.gender not in valid_genders:
            profile.gender = ""
            profile.gender_other = ""
            changed_fields.extend(["gender", "gender_other"])
        elif profile.gender != "other" and profile.gender_other:
            profile.gender_other = ""
            changed_fields.append("gender_other")
        if changed_fields:
            profile.save(update_fields=changed_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0021_studentprofile_frequency_fields_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SupportInvestigation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="customuser",
            name="customuser_role_valid",
        ),
        migrations.AddField(
            model_name="customuser",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deactivated_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deactivation_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("realtor", "Realtor"),
                    ("moderator", "Moderator"),
                    ("support", "Support"),
                    ("platform_admin", "Platform Admin"),
                ],
                db_index=True,
                default="student",
                help_text="Access level for the housing platform.",
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_existing_access_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="adminprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("age__isnull", True), models.Q(("age__gte", 16), ("age__lte", 99)), _connector="OR"
                ),
                name="admin_profile_age_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="adminprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gender__in", ("male", "female", "other", "prefer_not")), ("gender", ""), _connector="OR"
                ),
                name="admin_profile_gender_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["student", "realtor", "moderator", "support", "platform_admin"])),
                name="customuser_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("age__isnull", True), models.Q(("age__gte", 16), ("age__lte", 99)), _connector="OR"
                ),
                name="student_profile_age_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gender__in", ("male", "female", "other", "prefer_not")), ("gender", ""), _connector="OR"
                ),
                name="student_profile_gender_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("messy_level__in", (1, 2, 3, 4, 5)), ("messy_level__isnull", True), _connector="OR"
                ),
                name="student_profile_messy_level_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("guest_level__in", (1, 2, 3, 4, 5)), ("guest_level__isnull", True), _connector="OR"
                ),
                name="student_profile_guest_level_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("bedtime__isnull", True), models.Q(("bedtime__gte", 0), ("bedtime__lte", 23)), _connector="OR"
                ),
                name="student_profile_bedtime_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("noise_level__in", (1, 2, 3, 4, 5)), ("noise_level__isnull", True), _connector="OR"
                ),
                name="student_profile_noise_level_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("drink__in", (1, 2, 3, 4, 5)), ("drink__isnull", True), _connector="OR"),
                name="student_profile_drink_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("party__in", (1, 2, 3, 4, 5)), ("party__isnull", True), _connector="OR"),
                name="student_profile_party_valid",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportinvestigation",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_support_investigations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportinvestigation",
            name="opened_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opened_support_investigations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportinvestigation",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_investigations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["target_type", "target_id"], name="audit_event_target_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["created_at"], name="audit_event_created_idx"),
        ),
        migrations.AddIndex(
            model_name="supportinvestigation",
            index=models.Index(fields=["subject", "expires_at"], name="support_inv_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="supportinvestigation",
            index=models.Index(fields=["opened_by", "expires_at"], name="support_inv_opened_idx"),
        ),
    ]
