# Generated by Django 5.2.13 on 2026-04-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_auditevent_supportinvestigation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("safety", "Safety concern"),
                            ("harassment", "Harassment or abusive behavior"),
                            ("spam", "Spam"),
                            ("impersonation", "Impersonation"),
                            ("scam", "Scam or suspicious behavior"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserReportUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("note", "Comment added"),
                            ("in_review", "Moved to in review"),
                            ("dismissed", "Dismissed"),
                            ("resolved", "Resolved"),
                            ("reopened", "Reopened"),
                            ("warned", "User warned"),
                            ("roommate_restricted", "Roommate access restricted"),
                            ("user_deactivated", "Account deactivated"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_report_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="users.userreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="userreport",
            index=models.Index(fields=["status", "created_at"], name="user_report_status_idx"),
        ),
        migrations.AddIndex(
            model_name="userreport",
            index=models.Index(fields=["reported_user", "status"], name="user_report_target_idx"),
        ),
        migrations.AddIndex(
            model_name="userreport",
            index=models.Index(fields=["reporter", "created_at"], name="user_report_reporter_idx"),
        ),
        migrations.AddIndex(
            model_name="userreportupdate",
            index=models.Index(fields=["report", "created_at"], name="user_rep_upd_report_idx"),
        ),
        migrations.AddIndex(
            model_name="userreportupdate",
            index=models.Index(fields=["actor", "created_at"], name="user_rep_upd_actor_idx"),
        ),
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason__in", ("safety", "harassment", "spam", "impersonation", "scam", "other"))),
                name="user_report_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("open", "in_review", "resolved", "dismissed"))),
                name="user_report_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["open", "in_review"])),
                fields=("reported_user", "reporter"),
                name="user_report_active_unique",
            ),
        ),
    ]
