# Generated by Django 5.2.13 on 2026-04-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_userreport_userreportupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="roommate_access_restricted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="roommate_access_restricted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roommate_access_restrictions_applied",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="roommate_access_restriction_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
