# Generated by Django 5.2.13 on 2026-04-28 04:10

from django.db import migrations, models


def populate_profile_verification_defaults(apps, schema_editor):
    student_profile = apps.get_model("users", "StudentProfile")
    admin_profile = apps.get_model("users", "AdminProfile")
    student_profile.objects.filter(
        institution_status="",
        user__profile_completed_at__isnull=False,
    ).update(institution_status="undergraduate")
    admin_profile.objects.filter(
        organization_type="",
        user__role="realtor",
        user__profile_completed_at__isnull=False,
    ).update(organization_type="individual_owner")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_customuser_warning_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userreport",
            name="user_report_reason_valid",
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="organization_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual_owner", "Individual owner"),
                    ("property_company", "Property company"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="institution_status",
            field=models.CharField(
                blank=True,
                choices=[("undergraduate", "Undergraduate"), ("graduate", "Graduate"), ("alumni", "Alumni")],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("safety", "Safety concern"),
                    ("harassment", "Harassment or abusive behavior"),
                    ("spam", "Spam"),
                    ("impersonation", "Impersonation"),
                    ("scam", "Scam or suspicious behavior"),
                    ("inappropriate", "Inappropriate content"),
                    ("other", "Other"),
                ],
                max_length=24,
            ),
        ),
        migrations.RunPython(populate_profile_verification_defaults, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="adminprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("organization_type__in", ("individual_owner", "property_company", "other")),
                    ("organization_type", ""),
                    _connector="OR",
                ),
                name="admin_profile_organization_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("institution_status__in", ("undergraduate", "graduate", "alumni")),
                    ("institution_status", ""),
                    _connector="OR",
                ),
                name="student_profile_institution_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reason__in", ("safety", "harassment", "spam", "impersonation", "scam", "inappropriate", "other"))
                ),
                name="user_report_reason_valid",
            ),
        ),
    ]
