# Generated by Django 5.2.11 on 2026-03-16 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_listing_amenities_listing_bathrooms_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="listingimage",
            options={"ordering": ["id"]},
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["is_hidden", "created_at"], name="listing_feed_idx"),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="listing_end_date_gte_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(condition=models.Q(("price__gt", 0)), name="listing_price_gt_zero"),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(condition=models.Q(("rooms__gte", 1)), name="listing_rooms_gte_one"),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("bathrooms__gt", 0)),
                name="listing_bathrooms_gt_zero",
            ),
        ),
    ]
