# Generated by Django 5.2.11 on 2026-03-17 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_listinginquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["owner", "created_at"], name="listing_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status", "created_at"], name="listing_status_idx"),
        ),
    ]
