# Generated by Django 5.2.11 on 2026-03-17 17:00

from django.db import migrations, models

import listings.validators


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listing_listing_owner_idx_listing_listing_status_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=models.ImageField(
                upload_to="listing_photos/",
                validators=[listings.validators.validate_listing_image],
            ),
        ),
    ]
