# Generated by Django 5.2.11 on 2026-03-18 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_inquiries_to_conversations(apps, schema_editor):
    ListingConversation = apps.get_model("listings", "ListingConversation")
    ListingInquiry = apps.get_model("listings", "ListingInquiry")
    ListingMessage = apps.get_model("listings", "ListingMessage")

    for inquiry in ListingInquiry.objects.select_related("listing").order_by("created_at", "pk").iterator():
        message_body = (inquiry.message or "").strip()
        conversation = ListingConversation.objects.create(
            listing_id=inquiry.listing_id,
            owner_id=inquiry.listing.owner_id,
            participant_id=inquiry.sender_id,
            last_message_at=inquiry.created_at,
            last_message_preview=message_body[:280],
            owner_has_unread_messages=bool(message_body),
            participant_has_unread_messages=False,
        )
        ListingConversation.objects.filter(pk=conversation.pk).update(
            created_at=inquiry.created_at,
            last_message_at=inquiry.created_at,
        )

        if message_body:
            message = ListingMessage.objects.create(
                conversation_id=conversation.pk,
                sender_id=inquiry.sender_id,
                body=message_body,
            )
            ListingMessage.objects.filter(pk=message.pk).update(created_at=inquiry.created_at)


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_alter_listingimage_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_message_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_message_preview", models.CharField(blank=True, max_length=280)),
                ("owner_has_unread_messages", models.BooleanField(default=False)),
                ("participant_has_unread_messages", models.BooleanField(default=False)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="listings.listing",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_listing_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="listings.listingconversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RunPython(
            migrate_inquiries_to_conversations,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="ListingInquiry",
        ),
        migrations.AddIndex(
            model_name="listingconversation",
            index=models.Index(fields=["listing", "last_message_at"], name="listing_conv_listing_idx"),
        ),
        migrations.AddIndex(
            model_name="listingconversation",
            index=models.Index(
                fields=["owner", "owner_has_unread_messages", "last_message_at"],
                name="listing_conv_owner_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listingconversation",
            index=models.Index(
                fields=[
                    "participant",
                    "participant_has_unread_messages",
                    "last_message_at",
                ],
                name="listing_conv_participant_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingconversation",
            constraint=models.UniqueConstraint(
                fields=("listing", "participant"),
                name="unique_listing_conversation_participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingconversation",
            constraint=models.CheckConstraint(
                condition=models.Q(("owner", models.F("participant")), _negated=True),
                name="listing_conversation_owner_ne_participant",
            ),
        ),
        migrations.AddIndex(
            model_name="listingmessage",
            index=models.Index(fields=["conversation", "created_at"], name="listing_message_thread_idx"),
        ),
        migrations.AddIndex(
            model_name="listingmessage",
            index=models.Index(fields=["sender", "created_at"], name="listing_message_sender_idx"),
        ),
    ]
