# Generated by Django 5.2.11 on 2026-03-20 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_move_messaging_to_communications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="application_fee",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="parking_fee",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="security_deposit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="utilities_estimate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("utilities_estimate__isnull", True),
                    ("utilities_estimate__gte", 0),
                    _connector="OR",
                ),
                name="listing_utilities_estimate_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parking_fee__isnull", True),
                    ("parking_fee__gte", 0),
                    _connector="OR",
                ),
                name="listing_parking_fee_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("security_deposit__isnull", True),
                    ("security_deposit__gte", 0),
                    _connector="OR",
                ),
                name="listing_security_deposit_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("application_fee__isnull", True),
                    ("application_fee__gte", 0),
                    _connector="OR",
                ),
                name="listing_application_fee_gte_zero",
            ),
        ),
    ]
