# Generated by Django 5.2.11 on 2026-03-22 06:45

from django.db import migrations, models


def clear_negative_listing_distance_to_campus(apps, schema_editor):
    Listing = apps.get_model("listings", "Listing")
    Listing.objects.filter(distance_to_campus__lt=0).update(distance_to_campus=None)


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0009_listing_application_fee_listing_parking_fee_and_more"),
    ]

    operations = [
        migrations.RunPython(
            clear_negative_listing_distance_to_campus,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("distance_to_campus__isnull", True),
                    ("distance_to_campus__gte", 0),
                    _connector="OR",
                ),
                name="listing_distance_to_campus_gte_zero",
            ),
        ),
    ]
