# Generated by Django 5.2.11 on 2026-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0010_listing_listing_distance_to_campus_gte_zero"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="listing",
            name="listing_feed_idx",
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["is_hidden", "status", "end_date", "created_at"],
                name="listing_public_idx",
            ),
        ),
    ]
