# Generated by Django 5.2.11 on 2026-03-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0011_remove_listing_listing_feed_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("lease_type__in", ("SUBLEASE", "FULL", "SHORT"))),
                name="listing_lease_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("AVAILABLE", "PENDING", "TAKEN"))),
                name="listing_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("property_type__in", ("apartment", "house", "studio", "dorm"))),
                name="listing_property_type_valid",
            ),
        ),
    ]
