# Generated by Django 5.2.11 on 2026-03-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0012_listing_listing_lease_type_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
