# Generated by Django 5.2.11 on 2026-03-29 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_existing_listings_as_approved(apps, schema_editor):
    Listing = apps.get_model("listings", "Listing")
    Listing.objects.update(
        approval_status="approved",
        submitted_for_approval_at=F("created_at"),
        reviewed_at=F("created_at"),
        approved_at=F("created_at"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0014_listingfavorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("scam", "Scam or suspicious"),
                            ("inaccurate", "Inaccurate listing details"),
                            ("safety", "Safety concern"),
                            ("spam", "Spam or duplicate"),
                            ("unavailable", "No longer available"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="approval_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="approval_status",
            field=models.CharField(
                choices=[("pending", "Pending review"), ("approved", "Approved"), ("rejected", "Rejected")],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="submitted_for_approval_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_existing_listings_as_approved, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["approval_status", "created_at"], name="listing_approval_idx"),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("approval_status__in", ("pending", "approved", "rejected"))),
                name="listing_approval_status_valid",
            ),
        ),
        migrations.AddField(
            model_name="listingreport",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="listings.listing"
            ),
        ),
        migrations.AddField(
            model_name="listingreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="listing_reports", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="listingreport",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listing_reports_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingreview",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="listing_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="listingreview",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="listings.listing"
            ),
        ),
        migrations.AddIndex(
            model_name="listingreport",
            index=models.Index(fields=["status", "created_at"], name="listing_report_status_idx"),
        ),
        migrations.AddIndex(
            model_name="listingreport",
            index=models.Index(fields=["listing", "status"], name="listing_report_listing_idx"),
        ),
        migrations.AddIndex(
            model_name="listingreport",
            index=models.Index(fields=["reporter", "created_at"], name="listing_report_reporter_idx"),
        ),
        migrations.AddConstraint(
            model_name="listingreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason__in", ("scam", "inaccurate", "safety", "spam", "unavailable", "other"))),
                name="listing_report_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("open", "in_review", "resolved", "dismissed"))),
                name="listing_report_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["open", "in_review"])),
                fields=("listing", "reporter"),
                name="listing_report_active_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="listingreview",
            index=models.Index(fields=["listing", "updated_at"], name="listing_review_listing_idx"),
        ),
        migrations.AddIndex(
            model_name="listingreview",
            index=models.Index(fields=["author", "updated_at"], name="listing_review_author_idx"),
        ),
        migrations.AddConstraint(
            model_name="listingreview",
            constraint=models.UniqueConstraint(fields=("listing", "author"), name="listing_review_unique"),
        ),
        migrations.AddConstraint(
            model_name="listingreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)), name="listing_review_rating_valid"
            ),
        ),
    ]
