# Generated by Django 5.2.11 on 2026-03-31 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0015_listingreport_listingreview_listing_approval_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingReportUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("note", "Comment added"),
                            ("in_review", "Moved to in review"),
                            ("dismissed", "Dismissed"),
                            ("listing_closed", "Listing removed from marketplace"),
                            ("reopened", "Reopened"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_report_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="updates", to="listings.listingreport"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["report", "created_at"], name="list_rep_upd_report_idx"),
                    models.Index(fields=["actor", "created_at"], name="list_rep_upd_actor_idx"),
                ],
            },
        ),
    ]
