# Generated by Django 5.2.11 on 2026-04-01 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0016_listingreportupdate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoommatePost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                (
                    "housing_status",
                    models.CharField(
                        choices=[
                            ("have_home", "Already have a place"),
                            ("need_home", "Still need a place"),
                            ("flexible", "Open to either"),
                        ],
                        db_index=True,
                        default="flexible",
                        max_length=16,
                    ),
                ),
                ("current_group_size", models.PositiveSmallIntegerField(default=1)),
                ("open_spots", models.PositiveSmallIntegerField(default=1)),
                ("budget_min", models.DecimalField(decimal_places=0, max_digits=8)),
                ("budget_max", models.DecimalField(decimal_places=0, max_digits=8)),
                ("move_in_date", models.DateField(db_index=True)),
                ("neighborhoods", models.CharField(blank=True, max_length=240)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_post",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["is_active", "updated_at"], name="roommate_post_active_idx"),
                    models.Index(fields=["housing_status", "move_in_date"], name="roommate_post_housing_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("housing_status__in", ("have_home", "need_home", "flexible"))),
                        name="roommate_post_housing_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("current_group_size__gte", 1)), name="roommate_post_group_size_gte_one"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("open_spots__gte", 1)), name="roommate_post_open_spots_gte_one"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("budget_min__gte", 0)), name="roommate_post_budget_min_gte_zero"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("budget_max__gte", 0)), name="roommate_post_budget_max_gte_zero"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("budget_max__gte", models.F("budget_min"))),
                        name="roommate_post_budget_max_gte_min",
                    ),
                ],
            },
        ),
    ]
