# Generated by Django 5.2.11 on 2026-04-06 00:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0017_roommatepost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommatepost",
            name="open_spots",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.RemoveConstraint(
            model_name="roommatepost",
            name="roommate_post_open_spots_gte_one",
        ),
        migrations.AddConstraint(
            model_name="roommatepost",
            constraint=models.CheckConstraint(
                condition=(
                    Q(housing_status="have_home", open_spots__gte=1)
                    | Q(housing_status__in=["need_home"], open_spots__isnull=True)
                    | Q(housing_status__in=["need_home"], open_spots__gte=1)
                ),
                name="roommate_post_open_spots_valid",
            ),
        ),
    ]
