# Generated by Django 5.2.11 on 2026-04-07 03:41

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def normalize_roommate_posts(apps, schema_editor):
    RoommatePost = apps.get_model("listings", "RoommatePost")
    RoommatePost.objects.filter(housing_status="flexible").update(housing_status="need_home")
    RoommatePost.objects.filter(housing_status="have_home", open_spots__isnull=True).update(open_spots=1)
    RoommatePost.objects.filter(housing_status="have_home", open_spots__lt=1).update(open_spots=1)


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0018_roommatepost_open_spots_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_roommate_posts, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="roommatepost",
            name="roommate_post_housing_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="roommatepost",
            name="roommate_post_open_spots_valid",
        ),
        migrations.AlterField(
            model_name="roommatepost",
            name="housing_status",
            field=models.CharField(
                choices=[("have_home", "Already have a place"), ("need_home", "Still need a place")],
                db_index=True,
                default="need_home",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="roommatepost",
            constraint=models.CheckConstraint(
                condition=Q(housing_status__in=("have_home", "need_home")),
                name="roommate_post_housing_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="roommatepost",
            constraint=models.CheckConstraint(
                condition=(
                    Q(housing_status="have_home", open_spots__gte=1)
                    | Q(housing_status__in=["need_home"], open_spots__isnull=True)
                    | Q(housing_status__in=["need_home"], open_spots__gte=1)
                ),
                name="roommate_post_open_spots_valid",
            ),
        ),
    ]
