# Generated by Django 5.2.12 on 2026-04-07 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0018_roommate_post_fk"),
        ("listings", "0018_roommategroupmembership_alter_roommatepost_author_and_more"),
    ]

    operations = []
