# Generated by Django 5.2.11 on 2026-04-11 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0018_roommategroupmembership_alter_roommatepost_author_and_more"),
        ("listings", "0019_remove_roommatepost_roommate_post_housing_status_valid_and_more"),
    ]

    operations = []
