# Generated by Django 5.2.11 on 2026-04-11 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0020_merge_20260411_1528"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="roommatepost",
            name="roommate_post_open_spots_valid",
        ),
        migrations.AddConstraint(
            model_name="roommatepost",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("housing_status", "have_home"), ("open_spots__gte", 1)),
                    models.Q(
                        ("housing_status__in", ["need_home"]),
                        models.Q(("open_spots__isnull", True), ("open_spots__gte", 1), _connector="OR"),
                    ),
                    _connector="OR",
                ),
                name="roommate_post_open_spots_valid",
            ),
        ),
    ]
