# Generated by Django 5.2.11 on 2026-04-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0021_remove_roommatepost_roommate_post_open_spots_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommatepost",
            name="open_spots",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
