# Generated by Django 5.2.12 on 2026-04-14 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0020_alter_roommatepost_author"),
        ("listings", "0022_alter_roommatepost_open_spots"),
    ]

    operations = []
