# Generated by Django 5.2.12 on 2026-04-14 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0023_merge_20260414_1439"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roommategroupmembership",
            constraint=models.UniqueConstraint(fields=("user",), name="roommate_group_membership_one_group_per_user"),
        ),
    ]
