# Generated by Django 5.2.11 on 2026-04-19 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0024_one_group_per_user"),
        ("roommates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="archive_reason",
            field=models.CharField(
                blank=True,
                choices=[("owner", "Owner archived"), ("admin", "Admin archived"), ("report", "Archived from report")],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["archived_at", "created_at"], name="listing_archived_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["latitude", "longitude"], name="listing_lat_lng_idx"),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="RoommateGroup"),
                migrations.DeleteModel(name="RoommateGroupMembership"),
                migrations.DeleteModel(name="RoommatePost"),
            ],
        ),
    ]
