# Generated by Django 5.2.12 on 2026-04-26 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0025_remove_roommategroup_lead_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="broker_fee",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="documentation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lease", "Standard Lease"),
                    ("sublease", "Sublease Agreement"),
                    ("license", "License Agreement"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="landlord_approval_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="no_stairs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="original_lease_holder",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("broker_fee__isnull", True), ("broker_fee__gte", 0), _connector="OR"),
                name="listing_broker_fee_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("documentation_type", ""),
                    ("documentation_type__in", ("lease", "sublease", "license", "other")),
                    _connector="OR",
                ),
                name="listing_documentation_type_valid",
            ),
        ),
    ]
