# Generated by Django 5.2.13 on 2026-04-28 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0026_add_broker_fee_approval_lease_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="listingreport",
            name="listing_report_reason_valid",
        ),
        migrations.AddField(
            model_name="listing",
            name="renter_requirements",
            field=models.TextField(
                blank=True,
                help_text="Roommate or renter expectations such as smoking, cleanliness, guests, or paperwork.",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="space_type",
            field=models.CharField(
                choices=[
                    ("ENTIRE_UNIT", "Whole apartment / house"),
                    ("PRIVATE_ROOM", "Private room"),
                    ("SHARED_ROOM", "Shared room"),
                ],
                default="ENTIRE_UNIT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Available"), ("PENDING", "Pending"), ("TAKEN", "Rented")],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listingreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("scam", "Scam or suspicious"),
                    ("inaccurate", "Inaccurate listing details"),
                    ("safety", "Safety concern"),
                    ("spam", "Spam or duplicate"),
                    ("unavailable", "No longer available"),
                    ("inappropriate", "Inappropriate content"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("space_type__in", ("ENTIRE_UNIT", "PRIVATE_ROOM", "SHARED_ROOM"))),
                name="listing_space_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reason__in", ("scam", "inaccurate", "safety", "spam", "unavailable", "inappropriate", "other"))
                ),
                name="listing_report_reason_valid",
            ),
        ),
    ]
