"""
Django settings for vibecoders project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def env_int(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    return int(value)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SITE_PRODUCT_NAME = os.getenv("SITE_PRODUCT_NAME", "Padly").strip() or "Padly"
SITE_COMPANY_NAME = os.getenv("SITE_COMPANY_NAME", "Vibecoders").strip() or "Vibecoders"
LEGAL_DOCUMENT_VERSION = os.getenv("LEGAL_DOCUMENT_VERSION", "2026-03-18").strip() or "2026-03-18"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

LOCAL_DEBUG_COMMANDS = {
    "runserver",
    "test",
    "check",
    "migrate",
    "makemigrations",
    "showmigrations",
    "shell",
    "createsuperuser",
    "set_user_role",
}
RUNNING_TESTS = "test" in sys.argv
DEVELOPMENT_SECRET_KEY = "padly-local-dev-secret-key-2026-04-01-keep-out-of-production-only"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", any(command in sys.argv for command in LOCAL_DEBUG_COMMANDS))

configured_secret_key = os.getenv("DJANGO_SECRET_KEY", "").strip()
if configured_secret_key:
    SECRET_KEY = configured_secret_key
elif DEBUG:
    # Keep local sessions stable across autoreload when no explicit secret is configured.
    SECRET_KEY = DEVELOPMENT_SECRET_KEY
else:
    raise ImproperlyConfigured("Set DJANGO_SECRET_KEY when running with DJANGO_DEBUG=false.")

configured_allowed_hosts = env_list("DJANGO_ALLOWED_HOSTS", "")
if configured_allowed_hosts:
    ALLOWED_HOSTS = configured_allowed_hosts
elif DEBUG:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "testserver"]
else:
    raise ImproperlyConfigured("Set DJANGO_ALLOWED_HOSTS when running with DJANGO_DEBUG=false.")

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "daphne",
    "django.contrib.staticfiles",
    # Sub apps
    "core",
    "communications",
    "listings",
    "users",
    "django.contrib.sites",  # Required by allauth
    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "channels",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "users.middleware.CurrentLegalAcceptanceMiddleware",
    "users.middleware.ProfileCompletionMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Deny framing globally. Authenticated file previews opt into same-origin framing explicitly.
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
if env_bool("DJANGO_TRUST_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = env_bool("DJANGO_USE_X_FORWARDED_HOST", False)
TRUST_X_FORWARDED_FOR = env_bool("DJANGO_TRUST_X_FORWARDED_FOR", False)
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

ROOT_URLCONF = "vibecoders.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.branding",
            ],
        },
    },
]

WSGI_APPLICATION = "vibecoders.wsgi.application"
ASGI_APPLICATION = "vibecoders.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

if RUNNING_TESTS:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
LISTING_IMAGE_MAX_BYTES = env_int("LISTING_IMAGE_MAX_BYTES", 5 * 1024 * 1024)
LISTING_IMAGE_UPLOAD_LIMIT = env_int("LISTING_IMAGE_UPLOAD_LIMIT", 10)
LISTING_IMAGE_TOTAL_LIMIT = env_int("LISTING_IMAGE_TOTAL_LIMIT", 20)
LISTING_MAPS_ENABLED = env_bool("LISTING_MAPS_ENABLED", True)
LISTING_GEOCODING_ENABLED = False if RUNNING_TESTS else env_bool("LISTING_GEOCODING_ENABLED", True)
LISTING_GEOCODER_URL = os.getenv("LISTING_GEOCODER_URL", "https://photon.komoot.io/api/").strip()
LISTING_GEOCODER_URL = LISTING_GEOCODER_URL or "https://photon.komoot.io/api/"
LISTING_GEOCODER_USER_AGENT = os.getenv("LISTING_GEOCODER_USER_AGENT", f"{SITE_PRODUCT_NAME}/1.0").strip()
LISTING_GEOCODER_USER_AGENT = LISTING_GEOCODER_USER_AGENT or f"{SITE_PRODUCT_NAME}/1.0"
LISTING_GEOCODER_TIMEOUT_SECONDS = max(1, env_int("LISTING_GEOCODER_TIMEOUT_SECONDS", 4))
LISTING_GEOAPIFY_API_KEY = os.getenv("LISTING_GEOAPIFY_API_KEY", "").strip()
LISTING_GEOAPIFY_AUTOCOMPLETE_URL = os.getenv(
    "LISTING_GEOAPIFY_AUTOCOMPLETE_URL",
    "https://api.geoapify.com/v1/geocode/autocomplete",
).strip()
LISTING_GEOAPIFY_AUTOCOMPLETE_URL = (
    LISTING_GEOAPIFY_AUTOCOMPLETE_URL or "https://api.geoapify.com/v1/geocode/autocomplete"
)
LISTING_GEOAPIFY_MAP_STYLE_URL = os.getenv("LISTING_GEOAPIFY_MAP_STYLE_URL", "").strip()
if not LISTING_GEOAPIFY_MAP_STYLE_URL and LISTING_GEOAPIFY_API_KEY:
    LISTING_GEOAPIFY_MAP_STYLE_URL = (
        f"https://maps.geoapify.com/v1/styles/osm-liberty/style.json?apiKey={LISTING_GEOAPIFY_API_KEY}"
    )
LISTING_MAP_SATELLITE_STYLE_URL = os.getenv("LISTING_MAP_SATELLITE_STYLE_URL", "").strip() or "builtin://satellite"
LISTING_ADDRESS_AUTOCOMPLETE_RATE_LIMIT = env_int("LISTING_ADDRESS_AUTOCOMPLETE_RATE_LIMIT", 30)
LISTING_ADDRESS_AUTOCOMPLETE_RATE_WINDOW_SECONDS = env_int("LISTING_ADDRESS_AUTOCOMPLETE_RATE_WINDOW_SECONDS", 60)
LISTING_REPORT_RATE_LIMIT = env_int("LISTING_REPORT_RATE_LIMIT", 10)
LISTING_REPORT_RATE_WINDOW_SECONDS = env_int("LISTING_REPORT_RATE_WINDOW_SECONDS", 3600)
USER_FILE_MAX_BYTES = env_int("USER_FILE_MAX_BYTES", 10 * 1024 * 1024)
USER_FILE_TOTAL_LIMIT = env_int("USER_FILE_TOTAL_LIMIT", 25)
USER_FILE_UPLOAD_RATE_LIMIT = env_int("USER_FILE_UPLOAD_RATE_LIMIT", 25)
USER_FILE_UPLOAD_RATE_WINDOW_SECONDS = env_int("USER_FILE_UPLOAD_RATE_WINDOW_SECONDS", 300)
MESSAGE_SEND_RATE_LIMIT = env_int("MESSAGE_SEND_RATE_LIMIT", 20)
MESSAGE_SEND_RATE_WINDOW_SECONDS = env_int("MESSAGE_SEND_RATE_WINDOW_SECONDS", 60)
LOGIN_INIT_RATE_LIMIT = env_int("LOGIN_INIT_RATE_LIMIT", 10)
LOGIN_INIT_RATE_WINDOW_SECONDS = env_int("LOGIN_INIT_RATE_WINDOW_SECONDS", 300)
ACCOUNT_DELETION_RECENT_AUTH_SECONDS = env_int("ACCOUNT_DELETION_RECENT_AUTH_SECONDS", 1800)
DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").strip().upper() or "INFO"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "users.CustomUser"
STUDENT_EMAIL_DOMAINS = env_list("STUDENT_EMAIL_DOMAINS", "bc.edu")

# ALLAUTH SETTINGS
# -----------------------------------------------------------------------------
# These settings are required by allauth and are used to configure the authentication process
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Django admin and permissions
    "allauth.account.auth_backends.AuthenticationBackend",  # Allauth
]

# Allauth config — regular signup/login disabled; Google OAuth only
SOCIALACCOUNT_ONLY = True
ACCOUNT_LOGIN_METHODS = {"email"}  # Required by allauth; actual blocking is via NoSignupAccountAdapter
ACCOUNT_SIGNUP_FIELDS = ["email*"]  # No password fields; actual blocking is via NoSignupAccountAdapter
ACCOUNT_EMAIL_VERIFICATION = "none"  # Google provides the verified email identity
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_STORE_TOKENS = False
ACCOUNT_LOGIN_BY_CODE_ENABLED = False
ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED = False
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = False
LOGIN_URL = "/accounts/login/"

LOGIN_REDIRECT_URL = "/users/dashboard/"  # Where to go after login
LOGOUT_REDIRECT_URL = "/"  # Where to go after logout

# Profile completion enforcement
PROFILE_COMPLETION_REQUIRED = False if RUNNING_TESTS else env_bool("PROFILE_COMPLETION_REQUIRED", True)

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "EMAIL_AUTHENTICATION": True,
        "AUTH_PARAMS": {"access_type": "online"},
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
        },
    },
}

ACCOUNT_ADAPTER = "users.adapters.NoSignupAccountAdapter"
SOCIALACCOUNT_ADAPTER = "users.adapters.MarketplaceSocialAccountAdapter"

CHANNEL_REDIS_URL = os.getenv("CHANNEL_REDIS_URL", "").strip()
if not DEBUG and not CHANNEL_REDIS_URL:
    raise ImproperlyConfigured("Set CHANNEL_REDIS_URL when running with DJANGO_DEBUG=false.")

if CHANNEL_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [CHANNEL_REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_LOG_LEVEL,
    },
}
