DEMO_USERNAME_PREFIX = "demo_"
DEMO_PASSWORD = "PadlyDemo!2026"
STALE_LEGAL_VERSION = "2025-01-01"

DEMO_PHOTOS = [
    {
        "key": "white_house_exterior",
        "filename": "white_house_exterior.jpg",
        "title": "White_house_(Unsplash).jpg",
        "source_page_url": "https://commons.wikimedia.org/wiki/File:White_house_(Unsplash).jpg",
        "download_url": "https://commons.wikimedia.org/wiki/Special:Redirect/file/White_house_(Unsplash).jpg",
        "sha256": "d5ef100e84c836da70c462f36fe0893e587c5feb91e0b8a5d0e7ded75737e43e",
        "author": "Frøy Hamstad",
        "license": "CC0 1.0",
        "description": "White house exterior with black trim and landscaped front entry.",
    },
    {
        "key": "apartment_high_rise_exterior",
        "filename": "apartment_high_rise_exterior.jpg",
        "title": "Apartment_High_Rise_Building_(Unsplash).jpg",
        "source_page_url": "https://commons.wikimedia.org/wiki/File:Apartment_High_Rise_Building_(Unsplash).jpg",
        "download_url": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Apartment_High_Rise_Building_(Unsplash).jpg",
        "sha256": "a7fff0fb3e0fcf6067fbf9a70c850d1f895c64d37966db03d81baad57fb9720f",
        "author": "Jimmy Chang",
        "license": "CC0 1.0",
        "description": "Urban apartment tower exterior against a blue sky.",
    },
    {
        "key": "blue_white_kitchen",
        "filename": "blue_white_kitchen.jpg",
        "title": "Blue_white_kitchen_interior_(Unsplash).jpg",
        "source_page_url": "https://commons.wikimedia.org/wiki/File:Blue_white_kitchen_interior_(Unsplash).jpg",
        "download_url": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Blue_white_kitchen_interior_(Unsplash).jpg",
        "sha256": "1030543c6e3b65863e9ee11c4a4f9da6dfa78bc93c7d20b93782fb16ffcd2fb0",
        "author": "NeONBRAND",
        "license": "CC0 1.0",
        "description": "Blue-and-white open kitchen with island and large windows.",
    },
    {
        "key": "living_room_brick",
        "filename": "living_room_brick.jpg",
        "title": "Furnished_living_room._(Unsplash).jpg",
        "source_page_url": "https://commons.wikimedia.org/wiki/File:Furnished_living_room._(Unsplash).jpg",
        "download_url": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Furnished_living_room._(Unsplash).jpg",
        "sha256": "f73d6744ddaff941ab2701e17ec5e11f66681368ecd00efd01f374938e39f9a4",
        "author": "Stephen Di Donato",
        "license": "CC0 1.0",
        "description": "Bright furnished living room with exposed brick and white sofa.",
    },
    {
        "key": "bedroom_window",
        "filename": "bedroom_window.jpg",
        "title": "Bedroom_window_(Unsplash).jpg",
        "source_page_url": "https://commons.wikimedia.org/wiki/File:Bedroom_window_(Unsplash).jpg",
        "download_url": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Bedroom_window_(Unsplash).jpg",
        "sha256": "42a5e7e0b3d7ffb9e089a0fa2b0467726ed616f9daf9cd6c4a3a441f0b452d37",
        "author": "Viktoria Hall-Waldhauser",
        "license": "CC0 1.0",
        "description": "Bedroom corner with bedding, blanket, and window light.",
    },
]

DEMO_USERS = [
    {
        "key": "nadia_admin",
        "username": "demo_nadia_admin",
        "email": "nadia.admin.demo@bc.edu",
        "first_name": "Nadia",
        "last_name": "Mercer",
        "role": "admin",
        "profile": {
            "preferred_name": "Nadia",
            "bio": "Operations admin account for moderation and support workflow testing.",
        },
        "is_staff": True,
        "is_superuser": True,
        "legal_state": "current",
    },
    {
        "key": "emily_realtor",
        "username": "demo_emily_realtor",
        "email": "emily.hart.demo@padly-realty.example",
        "first_name": "Emily",
        "last_name": "Hart",
        "role": "realtor",
        "profile": {
            "preferred_name": "Emily",
            "bio": "Leases student-friendly inventory around Brighton and Cleveland Circle.",
        },
        "legal_state": "current",
    },
    {
        "key": "jordan_realtor",
        "username": "demo_jordan_realtor",
        "email": "jordan.shaw.demo@padly-realty.example",
        "first_name": "Jordan",
        "last_name": "Shaw",
        "role": "realtor",
        "profile": {
            "preferred_name": "Jordan",
            "bio": "Handles compact apartments and furnished short-term inventory.",
        },
        "legal_state": "current",
    },
    {
        "key": "marco_realtor",
        "username": "demo_marco_realtor",
        "email": "marco.alvarez.demo@padly-realty.example",
        "first_name": "Marco",
        "last_name": "Alvarez",
        "role": "realtor",
        "profile": {
            "preferred_name": "Marco",
            "bio": "Focuses on family houses and multi-bedroom listings near the Green Line.",
        },
        "legal_state": "current",
    },
    {
        "key": "claire_brennan",
        "username": "demo_claire_brennan",
        "email": "claire.brennan.demo@bc.edu",
        "first_name": "Claire",
        "last_name": "Brennan",
        "role": "student",
        "profile": {
            "preferred_name": "Claire",
            "age": 21,
            "gender": "female",
            "major": "Nursing",
            "bio": "Junior nursing student who keeps a quiet home and likes early mornings.",
            "messy_level": 4,
            "guest_level": 2,
            "bedtime": 22,
            "noise_level": 2,
            "smoke": False,
            "drink": 2,
            "party": 1,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "owen_walsh",
        "username": "demo_owen_walsh",
        "email": "owen.walsh.demo@bc.edu",
        "first_name": "Owen",
        "last_name": "Walsh",
        "role": "student",
        "profile": {
            "preferred_name": "Owen",
            "age": 22,
            "gender": "male",
            "major": "Economics",
            "bio": "Senior economics major who is usually out for internships during the day.",
            "messy_level": 3,
            "guest_level": 3,
            "bedtime": 23,
            "noise_level": 3,
            "smoke": False,
            "drink": 3,
            "party": 2,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "riley_chen",
        "username": "demo_riley_chen",
        "email": "riley.chen.demo@bc.edu",
        "first_name": "Riley",
        "last_name": "Chen",
        "role": "student",
        "profile": {
            "preferred_name": "Riley",
            "age": 20,
            "gender": "other",
            "gender_other": "Non-binary",
            "major": "Computer Science",
            "bio": "CS student who wants good Wi-Fi, predictable chores, and calm weeknights.",
            "messy_level": 4,
            "guest_level": 2,
            "bedtime": 0,
            "noise_level": 2,
            "smoke": False,
            "drink": 2,
            "party": 1,
            "pets": True,
        },
        "legal_state": "current",
    },
    {
        "key": "sofia_patel",
        "username": "demo_sofia_patel",
        "email": "sofia.patel.demo@bc.edu",
        "first_name": "Sofia",
        "last_name": "Patel",
        "role": "student",
        "profile": {
            "preferred_name": "Sofia",
            "age": 21,
            "gender": "female",
            "major": "Psychology",
            "bio": "Junior who likes a social but respectful apartment and cooks most nights.",
            "messy_level": 3,
            "guest_level": 3,
            "bedtime": 23,
            "noise_level": 3,
            "smoke": False,
            "drink": 3,
            "party": 2,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "ava_martinez",
        "username": "demo_ava_martinez",
        "email": "ava.martinez.demo@bc.edu",
        "first_name": "Ava",
        "last_name": "Martinez",
        "role": "student",
        "profile": {
            "preferred_name": "Ava",
            "age": 19,
            "gender": "female",
            "major": "Biology",
            "bio": "Pre-med sophomore who wants a clean apartment and a short commute to labs.",
            "messy_level": 5,
            "guest_level": 2,
            "bedtime": 22,
            "noise_level": 1,
            "smoke": False,
            "drink": 1,
            "party": 1,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "marcus_green",
        "username": "demo_marcus_green",
        "email": "marcus.green.demo@bc.edu",
        "first_name": "Marcus",
        "last_name": "Green",
        "role": "student",
        "profile": {
            "preferred_name": "Marcus",
            "age": 22,
            "gender": "male",
            "major": "Finance",
            "bio": "Finance senior who wants easy transit access and a practical apartment setup.",
            "messy_level": 3,
            "guest_level": 4,
            "bedtime": 0,
            "noise_level": 3,
            "smoke": False,
            "drink": 3,
            "party": 3,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "noah_turner",
        "username": "demo_noah_turner",
        "email": "noah.turner.demo@bc.edu",
        "first_name": "Noah",
        "last_name": "Turner",
        "role": "student",
        "profile": {
            "preferred_name": "Noah",
            "age": 20,
            "gender": "male",
            "major": "Political Science",
            "bio": "Junior with a packed schedule who wants a reliable apartment and low drama.",
            "messy_level": 3,
            "guest_level": 2,
            "bedtime": 23,
            "noise_level": 2,
            "smoke": False,
            "drink": 2,
            "party": 2,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "priya_shah",
        "username": "demo_priya_shah",
        "email": "priya.shah.demo@bc.edu",
        "first_name": "Priya",
        "last_name": "Shah",
        "role": "student",
        "profile": {
            "preferred_name": "Priya",
            "age": 21,
            "gender": "female",
            "major": "Applied Mathematics",
            "bio": "Applied math major who is tidy, collaborative, and serious about shared-space communication.",
            "messy_level": 4,
            "guest_level": 2,
            "bedtime": 23,
            "noise_level": 2,
            "smoke": False,
            "drink": 2,
            "party": 1,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "liam_oconnell",
        "username": "demo_liam_oconnell",
        "email": "liam.oconnell.demo@bc.edu",
        "first_name": "Liam",
        "last_name": "O'Connell",
        "role": "student",
        "profile": {
            "preferred_name": "Liam",
            "age": 22,
            "gender": "male",
            "major": "History",
            "bio": "History major who likes a quiet apartment and splits chores without reminders.",
            "messy_level": 4,
            "guest_level": 2,
            "bedtime": 23,
            "noise_level": 2,
            "smoke": False,
            "drink": 2,
            "party": 1,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "nora_kim",
        "username": "demo_nora_kim",
        "email": "nora.kim.demo@bc.edu",
        "first_name": "Nora",
        "last_name": "Kim",
        "role": "student",
        "profile": {
            "preferred_name": "Nora",
            "age": 20,
            "gender": "female",
            "major": "Marketing",
            "bio": "Marketing student looking for a friendly apartment with clear boundaries and a good kitchen.",
            "messy_level": 3,
            "guest_level": 3,
            "bedtime": 23,
            "noise_level": 3,
            "smoke": False,
            "drink": 3,
            "party": 2,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "emma_rossi",
        "username": "demo_emma_rossi",
        "email": "emma.rossi.demo@bc.edu",
        "first_name": "Emma",
        "last_name": "Rossi",
        "role": "student",
        "profile": {
            "preferred_name": "Emma",
            "age": 21,
            "gender": "female",
            "major": "Communications",
            "bio": "Communications major who likes bright apartments and consistent house rules.",
            "messy_level": 4,
            "guest_level": 3,
            "bedtime": 23,
            "noise_level": 2,
            "smoke": False,
            "drink": 2,
            "party": 2,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "leo_grant",
        "username": "demo_leo_grant",
        "email": "leo.grant.demo@bc.edu",
        "first_name": "Leo",
        "last_name": "Grant",
        "role": "student",
        "profile": {
            "preferred_name": "Leo",
            "age": 22,
            "gender": "male",
            "major": "Environmental Studies",
            "bio": "Senior who bikes to campus and wants a practical shared apartment with low noise.",
            "messy_level": 4,
            "guest_level": 2,
            "bedtime": 22,
            "noise_level": 2,
            "smoke": False,
            "drink": 2,
            "party": 1,
            "pets": False,
        },
        "legal_state": "current",
    },
    {
        "key": "daniel_ruiz",
        "username": "demo_daniel_ruiz",
        "email": "daniel.ruiz.demo@bc.edu",
        "first_name": "Daniel",
        "last_name": "Ruiz",
        "role": "student",
        "profile": {
            "preferred_name": "Daniel",
            "age": 20,
            "gender": "male",
            "major": "English",
            "bio": "English major who wants a relaxed apartment with dependable roommates.",
            "messy_level": 3,
            "guest_level": 3,
            "bedtime": 0,
            "noise_level": 3,
            "smoke": False,
            "drink": 2,
            "party": 2,
            "pets": True,
        },
        "legal_state": "current",
    },
    {
        "key": "elena_park",
        "username": "demo_elena_park",
        "email": "elena.park.demo@bc.edu",
        "first_name": "Elena",
        "last_name": "Park",
        "role": "student",
        "profile": None,
        "legal_state": "stale",
    },
]

DEMO_LISTINGS = [
    {
        "key": "foster_three_bed",
        "owner": "emily_realtor",
        "title": "Brighton 3BR with sunroom on Foster Street",
        "address": "77 Foster St, Brighton, MA 02135",
        "price": "1550.00",
        "description": (
            "Three-bedroom with a front sunroom, roomy common area, and a short walk to Cleveland Circle. "
            "Good fit for students who want space without losing transit access."
        ),
        "start_offset_days": 20,
        "end_offset_days": 360,
        "lease_type": "FULL",
        "status": "AVAILABLE",
        "rooms": 3,
        "bathrooms": "1.5",
        "sq_ft": 1180,
        "property_type": "house",
        "has_yard": True,
        "has_parking": False,
        "is_furnished": False,
        "distance_to_campus": "0.9",
        "utilities_estimate": "115.00",
        "parking_fee": "0.00",
        "security_deposit": "1550.00",
        "application_fee": "25.00",
        "utilities_included": "Heat, Water",
        "pet_policy": "Cats considered with landlord approval.",
        "amenities": "Front sunroom, Hardwood floors, Shared backyard",
        "security_features": "Video intercom, Exterior lighting",
        "latitude": 42.3389,
        "longitude": -71.1546,
        "approval_status": "approved",
        "approval_notes": "Photos and address verified for student-facing launch demo.",
        "photos": ["white_house_exterior", "living_room_brick", "blue_white_kitchen"],
    },
    {
        "key": "comm_ave_studio",
        "owner": "jordan_realtor",
        "title": "Commonwealth Ave studio with roof deck access",
        "address": "1717 Commonwealth Ave, Brighton, MA 02135",
        "price": "1985.00",
        "description": (
            "Compact studio with updated finishes, building roof deck, and fast transit into campus and downtown. "
            "Best for one person who values location over square footage."
        ),
        "start_offset_days": 14,
        "end_offset_days": 330,
        "lease_type": "FULL",
        "status": "AVAILABLE",
        "rooms": 1,
        "bathrooms": "1.0",
        "sq_ft": 470,
        "property_type": "studio",
        "has_yard": False,
        "has_parking": False,
        "is_furnished": True,
        "distance_to_campus": "1.1",
        "utilities_estimate": "70.00",
        "parking_fee": "0.00",
        "security_deposit": "1985.00",
        "application_fee": "35.00",
        "utilities_included": "Heat, Hot water, WiFi",
        "pet_policy": "No pets.",
        "amenities": "Roof deck, Elevator, Furnished",
        "security_features": "Key fob entry, Lobby cameras",
        "latitude": 42.3408,
        "longitude": -71.1494,
        "approval_status": "approved",
        "approval_notes": "Furnished studio approved for marketplace search testing.",
        "photos": ["apartment_high_rise_exterior", "blue_white_kitchen", "living_room_brick"],
    },
    {
        "key": "chestnut_hill_sublet",
        "owner": "claire_brennan",
        "title": "Chestnut Hill 2BR sublet with off-street parking",
        "address": "191 Chestnut Hill Ave, Boston, MA 02135",
        "price": "1450.00",
        "description": (
            "Student-run two-bedroom sublet with one parking spot and a straightforward landlord. "
            "Works well for summer classes or early move-in before the main leasing cycle."
        ),
        "start_offset_days": 10,
        "end_offset_days": 120,
        "lease_type": "SUBLEASE",
        "status": "AVAILABLE",
        "rooms": 2,
        "bathrooms": "1.0",
        "sq_ft": 860,
        "property_type": "apartment",
        "has_yard": False,
        "has_parking": True,
        "is_furnished": False,
        "distance_to_campus": "0.7",
        "utilities_estimate": "90.00",
        "parking_fee": "75.00",
        "security_deposit": "900.00",
        "application_fee": "0.00",
        "utilities_included": "Water",
        "pet_policy": "No pets.",
        "amenities": "Parking spot, Dishwasher, Spacious closets",
        "security_features": "Exterior lights, Rear entry lock",
        "latitude": 42.3362,
        "longitude": -71.1521,
        "approval_status": "approved",
        "approval_notes": "Student-owned sublet approved after address confirmation.",
        "photos": ["white_house_exterior", "bedroom_window", "living_room_brick"],
    },
    {
        "key": "newton_group_house",
        "owner": "marco_realtor",
        "title": "Newton Centre 4BR house for an established group",
        "address": "15 Essex Rd, Newton Centre, MA 02459",
        "price": "1625.00",
        "description": (
            "Four-bedroom house with parking and a large basement hangout space. "
            "The layout works best for a full group rather than roommates joining one at a time."
        ),
        "start_offset_days": 30,
        "end_offset_days": 395,
        "lease_type": "FULL",
        "status": "AVAILABLE",
        "rooms": 4,
        "bathrooms": "2.0",
        "sq_ft": 1680,
        "property_type": "house",
        "has_yard": True,
        "has_parking": True,
        "is_furnished": False,
        "distance_to_campus": "2.3",
        "utilities_estimate": "140.00",
        "parking_fee": "0.00",
        "security_deposit": "1625.00",
        "application_fee": "25.00",
        "utilities_included": "Water",
        "pet_policy": "Small dogs considered.",
        "amenities": "Driveway, Basement lounge, Laundry",
        "security_features": "Motion lights, Smart deadbolt",
        "latitude": 42.3296,
        "longitude": -71.1931,
        "approval_status": "approved",
        "approval_notes": "Large house approved for group-search scenarios.",
        "photos": ["white_house_exterior", "living_room_brick", "blue_white_kitchen"],
    },
    {
        "key": "brookline_summer_sublet",
        "owner": "owen_walsh",
        "title": "Brookline Village furnished summer sublet",
        "address": "41 Station St, Brookline, MA 02445",
        "price": "1750.00",
        "description": (
            "Furnished one-bedroom close to the D line with enough room for a desk setup. "
            "Good for internships or summer clinical placements."
        ),
        "start_offset_days": 5,
        "end_offset_days": 110,
        "lease_type": "SHORT",
        "status": "AVAILABLE",
        "rooms": 1,
        "bathrooms": "1.0",
        "sq_ft": 640,
        "property_type": "apartment",
        "has_yard": False,
        "has_parking": False,
        "is_furnished": True,
        "distance_to_campus": "1.8",
        "utilities_estimate": "60.00",
        "parking_fee": "0.00",
        "security_deposit": "750.00",
        "application_fee": "0.00",
        "utilities_included": "Heat, Electricity, WiFi",
        "pet_policy": "No pets.",
        "amenities": "Furnished, Desk nook, Laundry in building",
        "security_features": "Secure front entry, Hallway lighting",
        "latitude": 42.3319,
        "longitude": -71.1218,
        "approval_status": "approved",
        "approval_notes": "Short-term furnished listing approved for commute testing.",
        "photos": ["living_room_brick", "bedroom_window", "blue_white_kitchen"],
    },
    {
        "key": "oak_square_one_bed",
        "owner": "emily_realtor",
        "title": "Oak Square 1BR with office nook",
        "address": "613 Washington St, Brighton, MA 02135",
        "price": "1825.00",
        "description": (
            "One-bedroom with a flexible office nook and a quieter street feel than the core BC corridor. "
            "Better for someone who wants privacy and a car-free commute."
        ),
        "start_offset_days": 18,
        "end_offset_days": 340,
        "lease_type": "FULL",
        "status": "AVAILABLE",
        "rooms": 1,
        "bathrooms": "1.0",
        "sq_ft": 710,
        "property_type": "apartment",
        "has_yard": False,
        "has_parking": False,
        "is_furnished": False,
        "distance_to_campus": "1.7",
        "utilities_estimate": "85.00",
        "parking_fee": "0.00",
        "security_deposit": "1825.00",
        "application_fee": "30.00",
        "utilities_included": "Water",
        "pet_policy": "Cats considered.",
        "amenities": "Office nook, Updated bath, Pantry storage",
        "security_features": "Deadbolt, Street-facing exterior lights",
        "latitude": 42.3492,
        "longitude": -71.1541,
        "approval_status": "approved",
        "approval_notes": "One-bed approved to give results pagination a smaller-unit option.",
        "photos": ["apartment_high_rise_exterior", "living_room_brick", "blue_white_kitchen"],
    },
    {
        "key": "brighton_taken",
        "owner": "jordan_realtor",
        "title": "Brighton 2BR already leased for fall",
        "address": "28 Chiswick Rd, Brighton, MA 02135",
        "price": "1495.00",
        "description": "Recently leased two-bedroom kept around for owner workspace and status testing.",
        "start_offset_days": 12,
        "end_offset_days": 340,
        "lease_type": "FULL",
        "status": "TAKEN",
        "rooms": 2,
        "bathrooms": "1.0",
        "sq_ft": 820,
        "property_type": "apartment",
        "has_yard": False,
        "has_parking": False,
        "is_furnished": False,
        "distance_to_campus": "1.0",
        "utilities_estimate": "95.00",
        "parking_fee": "0.00",
        "security_deposit": "1495.00",
        "application_fee": "25.00",
        "utilities_included": "Heat",
        "pet_policy": "No pets.",
        "amenities": "Laundry room, Updated flooring",
        "security_features": "Front door camera",
        "latitude": 42.3372,
        "longitude": -71.1533,
        "approval_status": "approved",
        "approval_notes": "Kept as a taken listing so owner dashboards are not all open inventory.",
        "photos": ["white_house_exterior", "living_room_brick"],
    },
    {
        "key": "south_street_pending",
        "owner": "claire_brennan",
        "title": "South Street apartment awaiting moderation",
        "address": "217 South St, Boston, MA 02135",
        "price": "1525.00",
        "description": "Draft listing queued for review with enough detail to populate the admin queue.",
        "start_offset_days": 24,
        "end_offset_days": 320,
        "lease_type": "FULL",
        "status": "AVAILABLE",
        "rooms": 2,
        "bathrooms": "1.0",
        "sq_ft": 790,
        "property_type": "apartment",
        "has_yard": False,
        "has_parking": False,
        "is_furnished": False,
        "distance_to_campus": "1.3",
        "utilities_estimate": "90.00",
        "parking_fee": "0.00",
        "security_deposit": "1525.00",
        "application_fee": "25.00",
        "utilities_included": "Water",
        "pet_policy": "No pets.",
        "amenities": "Updated windows, Basic laundry room",
        "security_features": "Deadbolt",
        "latitude": 42.3436,
        "longitude": -71.1587,
        "approval_status": "pending",
        "approval_notes": "",
        "photos": ["white_house_exterior", "blue_white_kitchen"],
    },
    {
        "key": "lake_street_rejected",
        "owner": "jordan_realtor",
        "title": "Lake Street listing rejected for mismatched details",
        "address": "19 Lake St, Brighton, MA 02135",
        "price": "1395.00",
        "description": "Rejected listing kept to exercise owner messaging and approval-note surfaces.",
        "start_offset_days": 16,
        "end_offset_days": 300,
        "lease_type": "FULL",
        "status": "AVAILABLE",
        "rooms": 2,
        "bathrooms": "1.0",
        "sq_ft": 760,
        "property_type": "apartment",
        "has_yard": False,
        "has_parking": False,
        "is_furnished": False,
        "distance_to_campus": "0.8",
        "utilities_estimate": "85.00",
        "parking_fee": "0.00",
        "security_deposit": "1395.00",
        "application_fee": "20.00",
        "utilities_included": "Heat",
        "pet_policy": "No pets.",
        "amenities": "Coin laundry, Galley kitchen",
        "security_features": "Entry buzzer",
        "latitude": 42.3378,
        "longitude": -71.1582,
        "approval_status": "rejected",
        "approval_notes": (
            "Exterior photo set does not match the claimed unit layout. Re-submit with current interior photos."
        ),
        "photos": ["white_house_exterior", "bedroom_window"],
    },
    {
        "key": "beacon_owner_archived",
        "owner": "owen_walsh",
        "title": "Beacon Street 2BR archived after lease signing",
        "address": "1479 Beacon St, Brookline, MA 02446",
        "price": "1680.00",
        "description": (
            "Formerly active listing that the owner archived after signing a lease with someone off-platform."
        ),
        "start_offset_days": 8,
        "end_offset_days": 220,
        "lease_type": "SUBLEASE",
        "status": "AVAILABLE",
        "rooms": 2,
        "bathrooms": "1.0",
        "sq_ft": 840,
        "property_type": "apartment",
        "has_yard": False,
        "has_parking": False,
        "is_furnished": True,
        "distance_to_campus": "1.6",
        "utilities_estimate": "65.00",
        "parking_fee": "0.00",
        "security_deposit": "800.00",
        "application_fee": "0.00",
        "utilities_included": "Heat, WiFi",
        "pet_policy": "No pets.",
        "amenities": "Furnished, Desk area, Updated lighting",
        "security_features": "Keypad entry",
        "latitude": 42.3425,
        "longitude": -71.1216,
        "approval_status": "approved",
        "approval_notes": "Approved before owner archived after signing elsewhere.",
        "archive": {
            "by": "owen_walsh",
            "reason": "owner",
            "notes": "Archived after the landlord finalized an off-platform lease signing.",
        },
        "photos": ["apartment_high_rise_exterior", "living_room_brick", "bedroom_window"],
    },
    {
        "key": "hammond_pond_report_archived",
        "owner": "marco_realtor",
        "title": "Hammond Pond Parkway listing removed after report review",
        "address": "250 Hammond Pond Pkwy, Newton, MA 02467",
        "price": "1725.00",
        "description": "Listing that stays in the database for moderation history after a report-driven archive.",
        "start_offset_days": 22,
        "end_offset_days": 365,
        "lease_type": "FULL",
        "status": "AVAILABLE",
        "rooms": 2,
        "bathrooms": "1.0",
        "sq_ft": 930,
        "property_type": "apartment",
        "has_yard": False,
        "has_parking": True,
        "is_furnished": False,
        "distance_to_campus": "2.0",
        "utilities_estimate": "105.00",
        "parking_fee": "80.00",
        "security_deposit": "1725.00",
        "application_fee": "25.00",
        "utilities_included": "Water",
        "pet_policy": "No pets.",
        "amenities": "Parking, Dishwasher, Extra storage",
        "security_features": "Cameras in lobby, Keyed entry",
        "latitude": 42.3275,
        "longitude": -71.1762,
        "approval_status": "approved",
        "approval_notes": "Initially approved before a student report closed the listing.",
        "photos": ["white_house_exterior", "blue_white_kitchen", "living_room_brick"],
    },
]

DEMO_LISTING_THREADS = [
    {
        "listing": "foster_three_bed",
        "participant": "riley_chen",
        "messages": [
            ("participant", "Hi Emily, is the sunroom large enough to fit a desk and a reading chair?"),
            ("owner", "Yes. The current tenants use it as a study space and it gets solid afternoon light."),
            ("participant", "Great. Can you confirm whether heat is included and if the backyard is shared?"),
            ("owner", "Heat is included, and the backyard is shared with the first-floor unit."),
        ],
        "review": {
            "author": "riley_chen",
            "rating": 5,
            "comment": "Fast replies, accurate photos, and the unit matched the showing.",
        },
    },
    {
        "listing": "comm_ave_studio",
        "participant": "marcus_green",
        "messages": [
            ("participant", "Does the building allow short summer extensions if my internship runs past August?"),
            ("owner", "Usually yes, but it depends on renewal timing. I can confirm with management this week."),
            ("participant", "Thanks. Also checking whether the roof deck stays open late enough for after-work use."),
            ("owner", "It closes at 10 PM, and there is fob access through the lobby."),
        ],
        "review": {
            "author": "marcus_green",
            "rating": 4,
            "comment": "Small but well represented, and the landlord response time was solid.",
        },
    },
    {
        "listing": "chestnut_hill_sublet",
        "participant": "ava_martinez",
        "messages": [
            ("participant", "Hi Claire, would the parking spot work for a compact SUV?"),
            ("owner", "Yes, it fits my RAV4 now. The driveway is tight but manageable."),
            ("participant", "That helps. Is the second bedroom quiet enough for overnight exam prep?"),
            ("owner", "Definitely. It faces the back of the building and stays pretty quiet."),
        ],
        "review": {
            "author": "ava_martinez",
            "rating": 5,
            "comment": "Owner was straightforward and the sublet details were easy to verify.",
        },
    },
    {
        "listing": "brookline_summer_sublet",
        "participant": "noah_turner",
        "messages": [
            ("participant", "Is the desk nook separate enough for remote work during the day?"),
            ("owner", "Yes, it is off the living area and gets enough natural light for video calls."),
            ("participant", "Good to know. I may need a move-in before the listed start date by a few days."),
            ("owner", "That should be workable as long as the building confirms turnover timing."),
        ],
    },
    {
        "listing": "beacon_owner_archived",
        "participant": "emma_rossi",
        "messages": [
            ("participant", "Hi Owen, is the sublet furnished exactly as shown in the photos?"),
            ("owner", "Yes, except the desk chair changed. Bed, sofa, and dining set stay."),
            ("participant", "Thanks. I saw the listing go archived later, so I just wanted the thread for reference."),
            ("owner", "Right, I archived it after the landlord finalized another renter."),
        ],
    },
    {
        "listing": "hammond_pond_report_archived",
        "participant": "sofia_patel",
        "messages": [
            ("participant", "Do you have an updated floor plan? The current photos look like a different layout."),
            ("owner", "I can send one later today."),
            ("participant", "Okay. I also noticed the parking fee was missing from the description."),
            ("owner", "Thanks for flagging that."),
        ],
    },
]

DEMO_LISTING_FAVORITES = [
    ("riley_chen", "comm_ave_studio"),
    ("riley_chen", "newton_group_house"),
    ("ava_martinez", "foster_three_bed"),
    ("marcus_green", "chestnut_hill_sublet"),
    ("noah_turner", "brookline_summer_sublet"),
    ("emma_rossi", "oak_square_one_bed"),
]

DEMO_REPORTS = [
    {
        "listing": "comm_ave_studio",
        "reporter": "noah_turner",
        "reason": "inaccurate",
        "details": "The furnished photos look staged and the listing does not say whether the desk is included.",
        "status_flow": [
            {
                "status": "open",
                "reviewer": None,
                "note": "Student asked for clarification on included furnishings.",
                "action": "note",
            }
        ],
    },
    {
        "listing": "brookline_summer_sublet",
        "reporter": "emma_rossi",
        "reason": "unavailable",
        "details": "Wanted to confirm whether the start date was still valid for the advertised sublet term.",
        "status_flow": [
            {
                "status": "in_review",
                "reviewer": "nadia_admin",
                "note": "Checking with the owner because availability timing may have changed.",
                "action": None,
            }
        ],
    },
    {
        "listing": "foster_three_bed",
        "reporter": "marcus_green",
        "reason": "other",
        "details": "Wanted confirmation that the backyard photo was from the same property and not a model image.",
        "status_flow": [
            {
                "status": "dismissed",
                "reviewer": "nadia_admin",
                "note": "Dismissed after the owner provided updated photos and matching parcel details.",
                "action": None,
            }
        ],
    },
    {
        "listing": "hammond_pond_report_archived",
        "reporter": "noah_turner",
        "reason": "inaccurate",
        "details": "The parking fee was omitted and the photo set did not match the floor plan provided in messages.",
        "status_flow": [
            {
                "status": "in_review",
                "reviewer": "nadia_admin",
                "note": "Escalated after the reporter shared screenshots from the thread.",
                "action": None,
            },
            {
                "status": "resolved",
                "reviewer": "nadia_admin",
                "note": "Listing archived because core pricing details and photo claims were materially inaccurate.",
                "action": None,
            },
        ],
    },
]

DEMO_ROOMMATE_SOLO_POSTS = [
    {
        "author": "riley_chen",
        "title": "Solo CS student looking for one clean roommate",
        "description": (
            "Looking for a two-person place with reliable Wi-Fi, space for a desk setup, and low-key weeknights. "
            "Open to Brighton or Brookline if the commute stays reasonable."
        ),
        "housing_status": "need_home",
        "current_group_size": 1,
        "open_spots": 1,
        "budget_min": "1300",
        "budget_max": "1700",
        "move_in_offset_days": 40,
        "neighborhoods": "Brighton, Brookline",
    },
    {
        "author": "sofia_patel",
        "title": "Junior looking to join a social but organized apartment",
        "description": (
            "I cook a lot, keep the common space tidy, and like a friendly apartment without constant guests. "
            "Happy to join an established group if the vibe is right."
        ),
        "housing_status": "need_home",
        "current_group_size": 1,
        "open_spots": 2,
        "budget_min": "1250",
        "budget_max": "1650",
        "move_in_offset_days": 48,
        "neighborhoods": "Cleveland Circle, Brighton",
    },
    {
        "author": "ava_martinez",
        "title": "Pre-med student seeking quiet roommate setup",
        "description": (
            "Need a place that stays calm on weeknights and works for early classes. "
            "Prefer one or two roommates max and an easy bus or train ride to campus."
        ),
        "housing_status": "need_home",
        "current_group_size": 1,
        "open_spots": 1,
        "budget_min": "1400",
        "budget_max": "1750",
        "move_in_offset_days": 35,
        "neighborhoods": "Chestnut Hill, Brookline",
    },
    {
        "author": "noah_turner",
        "title": "Junior with internship schedule looking for steady roommates",
        "description": (
            "Mostly out during the day, quiet at night, and prefer an apartment that feels predictable "
            "rather than chaotic. Flexible on neighborhood if the commute works."
        ),
        "housing_status": "need_home",
        "current_group_size": 1,
        "open_spots": 2,
        "budget_min": "1200",
        "budget_max": "1600",
        "move_in_offset_days": 42,
        "neighborhoods": "Brighton, Allston, Brookline",
    },
]

DEMO_ROOMMATE_GROUPS = [
    {
        "key": "priya_group",
        "lead": "priya_shah",
        "members": ["liam_oconnell"],
        "name": "Commonwealth Quiet Housemates",
        "description": (
            "Two upperclass students looking for one more roommate who values structure and clear communication."
        ),
        "post": {
            "title": "Two-person group looking for one more in Brighton",
            "description": (
                "We already know each other well, want a three-bedroom, and care about a calm shared routine "
                "more than parties."
            ),
            "housing_status": "need_home",
            "open_spots": 1,
            "budget_min": "1300",
            "budget_max": "1650",
            "move_in_offset_days": 45,
            "neighborhoods": "Brighton, Cleveland Circle",
        },
    },
    {
        "key": "leo_group",
        "lead": "leo_grant",
        "members": [],
        "name": "Green Line Practical Housemates",
        "description": "One student organizing a small apartment search focused on transit and low noise.",
        "post": {
            "title": "Starting a two-person search near the D line",
            "description": "Looking for one roommate who wants a practical place with decent transit and no drama.",
            "housing_status": "need_home",
            "open_spots": 1,
            "budget_min": "1250",
            "budget_max": "1600",
            "move_in_offset_days": 50,
            "neighborhoods": "Brookline, Newton Centre",
        },
    },
]

DEMO_DIRECT_THREADS = [
    {
        "participants": ("riley_chen", "sofia_patel"),
        "messages": [
            ("riley_chen", "Hey Sofia, your roommate post sounded aligned with what I am looking for."),
            ("sofia_patel", "Thanks. I liked that you care about keeping the common space calm on weeknights."),
            ("riley_chen", "Same. If you are open, I can send over a couple listings I bookmarked."),
            ("sofia_patel", "Definitely. Send anything near Brighton or Brookline first."),
        ],
    }
]

DEMO_GROUP_INVITES = [
    {
        "key": "nora_pending_approval",
        "creator": "priya_shah",
        "invitee": "nora_kim",
        "approval_responses": [],
        "invitee_response": None,
    },
    {
        "key": "emma_accepted",
        "creator": "leo_grant",
        "invitee": "emma_rossi",
        "approval_responses": [],
        "invitee_response": "accept",
    },
    {
        "key": "ava_pending_invitee",
        "creator": "daniel_ruiz",
        "invitee": "ava_martinez",
        "approval_responses": [],
        "invitee_response": None,
    },
]

DEMO_FAVORITE_ROOMMATES = [
    ("riley_chen", "sofia_patel"),
    ("sofia_patel", "riley_chen"),
    ("ava_martinez", "priya_shah"),
    ("noah_turner", "emma_rossi"),
]

DEMO_USER_FILES = [
    {
        "owner": "claire_brennan",
        "title": "Summer sublet checklist",
        "filename": "summer-sublet-checklist.txt",
        "content_type": "text/plain",
        "body": (
            "Keys to hand off\\nParking spot instructions\\nUtility transfer dates\\n"
            "Walkthrough photos before move-out\\n"
        ),
    },
    {
        "owner": "claire_brennan",
        "title": "Roommate budget worksheet",
        "filename": "roommate-budget.txt",
        "content_type": "text/plain",
        "body": "Target rent: 1450\\nUtilities buffer: 100\\nParking: 75\\nEmergency moving costs: 300\\n",
    },
    {
        "owner": "riley_chen",
        "title": "Questions for apartment tours",
        "filename": "tour-questions.txt",
        "content_type": "text/plain",
        "body": (
            "Ask about heat source\\nCheck outlet placement for desk\\n"
            "Ask who handles snow removal\\nConfirm guest policy\\n"
        ),
    },
    {
        "owner": "nadia_admin",
        "title": "Moderation resolution template",
        "filename": "moderation-resolution-template.pdf",
        "content_type": "application/pdf",
        "body": "Moderation resolution template for local demo data",
    },
]
