from datetime import timedelta

from django.utils import timezone

DEMO_USERS = [
    {
        "username": "maya_sullivan",
        "email": "maya.sullivan@bc.edu",
        "first_name": "Maya",
        "last_name": "Sullivan",
    },
    {
        "username": "liam_chen",
        "email": "liam.chen@bc.edu",
        "first_name": "Liam",
        "last_name": "Chen",
    },
    {
        "username": "zoe_kim",
        "email": "zoe.kim@bc.edu",
        "first_name": "Zoe",
        "last_name": "Kim",
    },
    {
        "username": "olivia_realtor",
        "email": "olivia@chestnuthillrealty.com",
        "first_name": "Olivia",
        "last_name": "Rivera",
    },
    {
        "username": "commave_team",
        "email": "team@commaveproperties.com",
        "first_name": "Comm Ave",
        "last_name": "Properties",
    },
]


def _offset_date(days, base_date=None):
    anchor = base_date or timezone.localdate()
    return anchor + timedelta(days=days)


def demo_listing_definitions(base_date=None):
    return [
        {
            "owner_email": "olivia@chestnuthillrealty.com",
            "title": "Cleveland Circle 2BR with parking",
            "address": "210 Sutherland Rd #3, Brighton, MA 02135",
            "price": "2350.00",
            "description": "Bright two-bedroom layout with a quick Green Line commute and off-street parking.",
            "start_date": _offset_date(14, base_date),
            "end_date": _offset_date(380, base_date),
            "lease_type": "FULL",
            "status": "AVAILABLE",
            "rooms": 2,
            "bathrooms": "1.0",
            "sq_ft": 980,
            "property_type": "apartment",
            "has_yard": False,
            "has_parking": True,
            "is_furnished": False,
            "distance_to_campus": "1.20",
            "utilities_included": "Water, trash",
            "pet_policy": "Cats considered with approval",
            "amenities": "Dishwasher, in-building laundry, private storage",
            "security_features": "Secure front entry",
            "is_hidden": False,
        },
        {
            "owner_email": "team@commaveproperties.com",
            "title": "South Street summer sublet",
            "address": "18 South St #2, Brookline, MA 02445",
            "price": "1450.00",
            "description": "Furnished summer sublet set up for internships, with flexible move-out timing.",
            "start_date": _offset_date(28, base_date),
            "end_date": _offset_date(120, base_date),
            "lease_type": "SUBLEASE",
            "status": "AVAILABLE",
            "rooms": 1,
            "bathrooms": "1.0",
            "sq_ft": 540,
            "property_type": "studio",
            "has_yard": False,
            "has_parking": False,
            "is_furnished": True,
            "distance_to_campus": "1.80",
            "utilities_included": "Heat, hot water, WiFi",
            "pet_policy": "No pets",
            "amenities": "Desk setup, window AC, laundry in building",
            "security_features": "Keypad building entry",
            "is_hidden": False,
        },
        {
            "owner_email": "maya.sullivan@bc.edu",
            "title": "Foster Street fall sublease near BC shuttle",
            "address": "114 Foster St #2, Brighton, MA 02135",
            "price": "1325.00",
            "description": "Student-friendly sublease with a quiet upstairs bedroom and easy access to campus.",
            "start_date": _offset_date(35, base_date),
            "end_date": _offset_date(180, base_date),
            "lease_type": "SUBLEASE",
            "status": "AVAILABLE",
            "rooms": 1,
            "bathrooms": "1.0",
            "sq_ft": 610,
            "property_type": "apartment",
            "has_yard": False,
            "has_parking": False,
            "is_furnished": True,
            "distance_to_campus": "0.90",
            "utilities_included": "Water, WiFi",
            "pet_policy": "No pets",
            "amenities": "Shared kitchen, furnished bedroom, bike storage",
            "security_features": "Video intercom",
            "is_hidden": False,
        },
        {
            "owner_email": "liam.chen@bc.edu",
            "title": "Commonwealth Ave 3BR with porch",
            "address": "1898 Commonwealth Ave #1, Brighton, MA 02135",
            "price": "3600.00",
            "description": "Three-bedroom apartment with a large front porch and room for a full roommate group.",
            "start_date": _offset_date(60, base_date),
            "end_date": _offset_date(425, base_date),
            "lease_type": "FULL",
            "status": "AVAILABLE",
            "rooms": 3,
            "bathrooms": "1.5",
            "sq_ft": 1380,
            "property_type": "apartment",
            "has_yard": False,
            "has_parking": True,
            "is_furnished": False,
            "distance_to_campus": "1.00",
            "utilities_included": "Water",
            "pet_policy": "Small pets case by case",
            "amenities": "Private porch, pantry, basement storage",
            "security_features": "Deadbolt entry",
            "is_hidden": False,
        },
        {
            "owner_email": "zoe.kim@bc.edu",
            "title": "Newton room in quiet house",
            "address": "42 Centre St, Newton, MA 02458",
            "price": "1180.00",
            "description": "Private bedroom in a shared house with two other BC students and a backyard.",
            "start_date": _offset_date(18, base_date),
            "end_date": _offset_date(300, base_date),
            "lease_type": "SHORT",
            "status": "AVAILABLE",
            "rooms": 1,
            "bathrooms": "1.0",
            "sq_ft": 420,
            "property_type": "house",
            "has_yard": True,
            "has_parking": True,
            "is_furnished": False,
            "distance_to_campus": "2.60",
            "utilities_included": "Water, landscaping",
            "pet_policy": "No pets",
            "amenities": "Backyard, storage closet, shared living room",
            "security_features": "Exterior motion lights",
            "is_hidden": False,
        },
        {
            "owner_email": "olivia@chestnuthillrealty.com",
            "title": "Chestnut Hill furnished 1BR",
            "address": "52 Hammond Pond Pkwy #7, Chestnut Hill, MA 02467",
            "price": "1895.00",
            "description": "Turnkey furnished one-bedroom with updated finishes and straightforward commute options.",
            "start_date": _offset_date(12, base_date),
            "end_date": _offset_date(250, base_date),
            "lease_type": "SHORT",
            "status": "AVAILABLE",
            "rooms": 1,
            "bathrooms": "1.0",
            "sq_ft": 720,
            "property_type": "apartment",
            "has_yard": False,
            "has_parking": True,
            "is_furnished": True,
            "distance_to_campus": "1.50",
            "utilities_included": "Heat, water, WiFi",
            "pet_policy": "No pets",
            "amenities": "Quartz kitchen, furnished living room, elevator",
            "security_features": "Lobby entry camera",
            "is_hidden": False,
        },
        {
            "owner_email": "team@commaveproperties.com",
            "title": "Brighton Center 4BR for roommate group",
            "address": "33 Corey Rd #2, Brighton, MA 02135",
            "price": "4800.00",
            "description": "Large four-bedroom layout designed for a full student group with generous common space.",
            "start_date": _offset_date(75, base_date),
            "end_date": _offset_date(440, base_date),
            "lease_type": "FULL",
            "status": "PENDING",
            "rooms": 4,
            "bathrooms": "2.0",
            "sq_ft": 1720,
            "property_type": "house",
            "has_yard": True,
            "has_parking": True,
            "is_furnished": False,
            "distance_to_campus": "1.40",
            "utilities_included": "Water",
            "pet_policy": "No pets",
            "amenities": "Rear deck, laundry room, basement storage",
            "security_features": "Smart lock",
            "is_hidden": False,
        },
        {
            "owner_email": "maya.sullivan@bc.edu",
            "title": "Reservoir dorm-style room share",
            "address": "79 Kirkwood Rd #3, Brighton, MA 02135",
            "price": "980.00",
            "description": "Budget-friendly room share with furnished common areas and flexible summer timing.",
            "start_date": _offset_date(7, base_date),
            "end_date": _offset_date(95, base_date),
            "lease_type": "SHORT",
            "status": "AVAILABLE",
            "rooms": 1,
            "bathrooms": "1.0",
            "sq_ft": 320,
            "property_type": "dorm",
            "has_yard": False,
            "has_parking": False,
            "is_furnished": True,
            "distance_to_campus": "1.10",
            "utilities_included": "Heat, electricity, WiFi",
            "pet_policy": "No pets",
            "amenities": "Shared kitchen, furnished common room, bike rack",
            "security_features": "Managed entry",
            "is_hidden": False,
        },
        {
            "owner_email": "liam.chen@bc.edu",
            "title": "Beacon Street 2BR with study nook",
            "address": "1748 Beacon St #4, Brookline, MA 02445",
            "price": "2780.00",
            "description": "Two-bedroom setup with an extra study corner, updated bath, and strong Green Line access.",
            "start_date": _offset_date(40, base_date),
            "end_date": _offset_date(405, base_date),
            "lease_type": "FULL",
            "status": "AVAILABLE",
            "rooms": 2,
            "bathrooms": "1.0",
            "sq_ft": 1025,
            "property_type": "apartment",
            "has_yard": False,
            "has_parking": False,
            "is_furnished": False,
            "distance_to_campus": "2.10",
            "utilities_included": "Heat",
            "pet_policy": "Cats allowed",
            "amenities": "Dishwasher, dining alcove, built-in shelving",
            "security_features": "Secure vestibule",
            "is_hidden": False,
        },
        {
            "owner_email": "team@commaveproperties.com",
            "title": "Owner-only draft in Oak Square",
            "address": "14 Brackett St #1, Brighton, MA 02135",
            "price": "2100.00",
            "description": "Hidden inventory for staging future availability before it goes live.",
            "start_date": _offset_date(90, base_date),
            "end_date": _offset_date(455, base_date),
            "lease_type": "FULL",
            "status": "AVAILABLE",
            "rooms": 2,
            "bathrooms": "1.0",
            "sq_ft": 890,
            "property_type": "apartment",
            "has_yard": False,
            "has_parking": True,
            "is_furnished": False,
            "distance_to_campus": "2.40",
            "utilities_included": "Water",
            "pet_policy": "No pets",
            "amenities": "Renovated kitchen, in-unit laundry",
            "security_features": "Deadbolt entry",
            "is_hidden": True,
        },
    ]


def demo_inquiry_definitions():
    return [
        {
            "listing_title": "Cleveland Circle 2BR with parking",
            "sender_email": "maya.sullivan@bc.edu",
            "message": "Interested for the fall semester. Is parking included in the monthly rent?",
        },
        {
            "listing_title": "South Street summer sublet",
            "sender_email": "liam.chen@bc.edu",
            "message": "I need a place from June through August. Are utilities fully covered?",
        },
        {
            "listing_title": "Chestnut Hill furnished 1BR",
            "sender_email": "zoe.kim@bc.edu",
            "message": (
                "Could you share the earliest move-in date and whether the unit is quiet enough for remote work?"
            ),
        },
        {
            "listing_title": "Commonwealth Ave 3BR with porch",
            "sender_email": "zoe.kim@bc.edu",
            "message": "A roommate group is interested. Are showings available this week?",
        },
    ]
